# Generated by Django 3.0.8 on 2020-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[], max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField()),
                ('body', models.TextField()),
                ('header_image', models.ImageField(blank=True, upload_to='uploads/service/header')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(choices=[], max_length=250)),
                ('category', models.CharField(choices=[], max_length=250)),
                ('related_to_name', models.CharField(blank=True, max_length=250)),
                ('category_name', models.CharField(blank=True, max_length=250)),
                ('location', models.ImageField(upload_to='uploads/service/images')),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
