# Generated by Django 3.0.8 on 2020-07-04 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20200704_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='dateofissue',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
